### PR TITLE
Added command line option to change log level

### PR DESCRIPTION
**Pull request by patgrosse**
A command line option (-l) makes it possible to limit the console output of wmediumd. It is meant to improve wmediumd's performance when using many interfaces and a lot of data.

### CODE REVIEW

**Comment by bcopeland** [comment]
Thanks, but I'd rather do this with a numeric log level  (perhaps following RFC 5424 priority levels) than with categories, because the strings kind of lock us into certain ways of doing things.  Would you consider taking that approach?

**Comment by patgrosse** [comment]
I will modify my changes with pleasure, but I at first I would like to clarify things.
You would like to have an integer parameter which takes the values from to 0 to 7 like it is defined in RFC-5424. The level "associations" I used are ok in general, just the usage of a character parameter is a bit messy.
If I got it right, this is the new scale I suggest:

> q: quiet, do not log anything when running

will become levels 0-2

> e: error, only log errors

will become level 3

>s: startup, log errors and startup msgs

will become level 4

>d: drops, log errors and startup msgs and packet drops

will become levels 5-6

>f: full (default), log everything

will become level 7

I will strip out these 4 booleans and store the log level directly as number.
Is this what you thought of?

**Comment by bcopeland** [comment]
On Mon, Dec 05, 2016 at 11:06:47AM -0800, Patrick Große wrote:
> I will modify my changes with pleasure, but I at first I would like to clarify things.
> You would like to have an integer parameter which takes the values from to 0 to 7 like it is defined in RFC-5424. The level "associations" I used are ok in general, just the usage of a character parameter is a bit messy.
> If I got it right, this is the new scale I suggest:
> 
> > q: quiet, do not log anything when running
> 
> will become levels 0-2
> 
> > e: error, only log errors
> 
> will become level 3
> 
> >s: startup, log errors and startup msgs
> 
> will become level 4
> 
> >d: drops, log errors and startup msgs and packet drops
> 
> will become levels 5-6
> 
> >f: full (default), log everything
> 
> will become level 7
> 
> I will strip out these 4 booleans and store the log level directly as number.
> Is this what you thought of?

Yup, that sounds perfect, thanks!

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by patgrosse** [comment]
I did the changes you requested, with the difference that startup messages are not assigned to level 4 (`LOG_WARN`) but level 5 (`LOG_NOTICE`) because of the definitions in RFC 5424 (it's not a warning condition).
I also removed the brackets in the usage message around the `-c` parameter because it is required and in POSIX.1-2008 brackets define optional parameters.

**Pull request merged**
