### PR TITLE
Add support for asymmetric loss probabilities

### PR DESCRIPTION
**Pull request by jcard0na**
In real deployments it is common to observe different loss probabilities on a link depending on the direction.  This patch adds support for simulating that.

### CODE REVIEW

**Comment by bcopeland** [comment]
Should we instead just allow asymmetric links everywhere?  And then, only if one side of the link is provided in the config, set the link to be symmetric (rather than default prob)?  It might make config parsing a little bit more complex but would be easier than duplicating each model twice.

**Comment by bcopeland** [comment]
(By the way, not asking you to do that work -- if you agree with that direction I can make the changes -- I took a peak at what it would take already.)

**Comment by jcard0na** [comment]
I agree that it would be useful to add support for asymmetric links to the SNR model, as opposite sides of a link can see different SNRs.  I don't think asymmetry can be added to the path loss model, but I could be misunderstanding that configuration (what is 'direction'?)

The suggestion to default to symmetric unless an asymmetric link is configured would definitely be nicer than introducing a separate model like I did.  I can try to rework the patch to do that (but feel free to beat me to it!).

**Comment by bcopeland** [comment]
Check out the feature/asymmetric-links branch I just pushed.  Only lightly tested but I think it should work ok.

**Comment by bcopeland** [comment]
made a pr for that so you can comment if you want.

**Comment by bcopeland** [comment]
Dropping this one since I merged the other change

**Pull request closed without merging**
