### PR TITLE
Add various simulation methods

### PR DESCRIPTION
**Pull request by masap**

### CODE REVIEW

**Comment by masap** [comment]
Is there any comment for this ?

**Comment by bcopeland** [comment]
In general it all looks quite nice though a bit to take in.  Can you share any evaluations you've made with the new simulations?

Some broad comments, keeping in mind I haven't really read that closely yet:

 * If we have error probability matrix, I don't think get_error_prob() is really that necessary (assuming they agree).  It would be better to just have one method for determining error probability given SNR.
 * I like having log path model and movement, I wrote up a similar one but never added due to not having energy to work out a config for them
 * Probably overkill to repeat the tmux stuff every time.  It would be better to just factor out the important parts (the wmediumd config file) and parameterize the rest
 * Could we just use links config in link probability case instead of the matrix?  i.e. switch between either having snr or fixed probability as the link value?

**Comment by masap** [comment]
Thanks for comments.

> Can you share any evaluations you've made with the new simulations?

Do you mean our test suite for these simulation ? If so, we are going to provide it.

> If we have error probability matrix, I don't think get_error_prob() is really that necessary (assuming they agree). It would be better to just have one method for determining error probability given SNR.

I leaved get_error_prob_from_snr() because I was afraid of breaking your existing local test code by replacing get_error_prob() with PER matrix. If you have no problem, I can fix the codes to use only matrix.

> I like having log path model and movement

Thanks (^^)

> Probably overkill to repeat the tmux stuff every time.

Yes. Checking ping results with "eyes" and kill tmux processes by `sudo killall tmux` is a bother. We have another solution for this. The system checks ping result automatically and close itself after test. We should modify the system for this wmediumd because out local wmediumd is little bit defferent. So we will provide the system after these codes are merged.

> Could we just use links config in link probability case instead of the matrix? i.e. switch between either having snr or fixed probability as the link value?

Yes. You can use all functionalities by specifying in config file.
* diamind.sh uses "links" for fiexd SNR
* diamind_error_prob.sh uses "error_probs" for fixed error probability
* diamind_log_distance.sh uses "path_loss" for log distance model

In addition, of course these three functionalities are exclusive.

**Comment by masap** [comment]
I have added some patches to remove get_error_prob().

**Comment by bcopeland** [comment]
So I started merging this piecemeal with some changes, but I think I'd like to take a different approach with the models.  I think we should just have a "model" parameter that specifies all the information for a given model, like you did for path_loss.  For backwards compat, the snr model can be specified inline without a model parameter, but could also be specified with model.  e.g.:
```
model: {
    type="path_loss"
    positions= (...)
    path_loss_exp = 3.5
    xg = 0.0
}
```
or 
```
model: {
    type = "snr"
    links = (...)
}
```
Also, I think instead of specifying full probability matrices in the prob model we should still use a links config to keep it simple.  We could specify default prob for anything not specifically named:
```
model: {
    type = "prob"
    default_prob = 0.0
    links = ((0, 1, 0.5), (0, 2, 0.0))
}
```

... or something like that.  Thoughts?

**Comment by masap** [comment]
>  I think we should just have a "model" parameter that specifies all the information for a given model, like you did for path_loss.

I see, it looks good to me.

> Also, I think instead of specifying full probability matrices in the prob model we should still use a links config to keep it simple. We could specify default prob for anything not specifically named:

I see, it looks reasonable to me.

I will modify both.

**Comment by masap** [comment]
I woule like to change this format 
```
model: {
    type="path_loss"
    positions= (...)
    path_loss_exp = 3.5
    xg = 0.0
}
```
to this format.
```
model: {
    type="path_loss"
    positions= (...)
    model_params = ("log_distance", 3.5, 0.0);
}
```
Because I would like to leave room for expansion to implement other several path loss models.

**Comment by masap** [comment]
I have modified all, could you review on these ?

In addition, I have changed my mind. I have implemented path_loss config like this.

```
model :
{
	type = "path_loss";
	positions = (
		(-50.0,   0.0),
		(  0.0,  20.0),
		(  0.0,   0.0),
		( 50.0,   0.0)
	);
	tx_powers = (15.0, 15.0, 15.0, 15.0);

	model_name = "log_distance";
	path_loss_exp = 3.5;
	xg = 0.0;
};
```

**Comment by bcopeland** [comment]
I merged all of this with a few merge fixups, please check that it still works as expected.  I did a quick test and things still seemed to go OK.

I plan to make some changes here though -- first, I think we can get rid of all the parsing code and build the PER lut in directly; second, I think we could get rid of the function pointers, though I haven't looked at it too closely yet.

**Comment by masap** [comment]
> I merged all of this with a few merge fixups, please check that it still works as expected. I did a quick test and things still seemed to go OK.

Thanks !
I have tested with new codes and it looks work.

> I plan to make some changes here though -- first, I think we can get rid of all the parsing code and build the PER lut in directly; second, I think we could get rid of the function pointers, though I haven't looked at it too closely yet.

Great !
After the modifications I will make test scripts based on the new framework.

**Pull request merged**
